TECH_STACKS = [
    {
        "id": "react",
        "name": "React",
        "category": "Frontend",
        "icon": "Globe",
        "description": "React with TypeScript and modern tooling",
        "frameworks": ["Vite", "Next.js", "Create React App"],
    },
    {
        "id": "vue",
        "name": "Vue.js",
        "category": "Frontend",
        "icon": "Globe",
        "description": "Vue 3 with Composition API",
        "frameworks": ["Vite", "Nuxt.js"],
    },
    {
        "id": "angular",
        "name": "Angular",
        "category": "Frontend",
        "icon": "Globe",
        "description": "Angular with TypeScript",
        "frameworks": ["Angular CLI"],
    },
    {
        "id": "svelte",
        "name": "Svelte",
        "category": "Frontend",
        "icon": "Globe",
        "description": "Svelte with SvelteKit",
        "frameworks": ["SvelteKit", "Vite"],
    },
    {
        "id": "html_css_js",
        "name": "HTML/CSS/JS",
        "category": "Frontend",
        "icon": "Globe",
        "description": "Vanilla HTML, CSS, and JavaScript",
        "frameworks": [],
    },
    {
        "id": "python_fastapi",
        "name": "Python FastAPI",
        "category": "Backend",
        "icon": "Server",
        "description": "FastAPI with async support",
        "frameworks": ["FastAPI"],
    },
    {
        "id": "python_django",
        "name": "Python Django",
        "category": "Backend",
        "icon": "Server",
        "description": "Django web framework",
        "frameworks": ["Django", "Django REST Framework"],
    },
    {
        "id": "python_flask",
        "name": "Python Flask",
        "category": "Backend",
        "icon": "Server",
        "description": "Flask microframework",
        "frameworks": ["Flask"],
    },
    {
        "id": "node_express",
        "name": "Node.js Express",
        "category": "Backend",
        "icon": "Server",
        "description": "Express.js with Node.js",
        "frameworks": ["Express"],
    },
    {
        "id": "node_nestjs",
        "name": "NestJS",
        "category": "Backend",
        "icon": "Server",
        "description": "NestJS with TypeScript",
        "frameworks": ["NestJS"],
    },
    {
        "id": "go",
        "name": "Go",
        "category": "Backend",
        "icon": "Server",
        "description": "Go with standard library or Gin",
        "frameworks": ["Standard Library", "Gin", "Echo"],
    },
    {
        "id": "rust",
        "name": "Rust",
        "category": "Backend",
        "icon": "Server",
        "description": "Rust with Actix or Axum",
        "frameworks": ["Actix", "Axum"],
    },
    {
        "id": "java_spring",
        "name": "Java Spring Boot",
        "category": "Backend",
        "icon": "Server",
        "description": "Spring Boot with Java/Kotlin",
        "frameworks": ["Spring Boot"],
    },
    {
        "id": "react_native",
        "name": "React Native",
        "category": "Mobile",
        "icon": "Smartphone",
        "description": "Cross-platform mobile with React Native",
        "frameworks": ["Expo", "React Native CLI"],
    },
    {
        "id": "flutter",
        "name": "Flutter",
        "category": "Mobile",
        "icon": "Smartphone",
        "description": "Cross-platform mobile with Flutter/Dart",
        "frameworks": ["Flutter"],
    },
    {
        "id": "python_script",
        "name": "Python Script",
        "category": "Scripts & CLI",
        "icon": "Terminal",
        "description": "Python scripts and CLI tools",
        "frameworks": ["Click", "Typer", "argparse"],
    },
    {
        "id": "bash_script",
        "name": "Bash Script",
        "category": "Scripts & CLI",
        "icon": "Terminal",
        "description": "Shell scripts and automation",
        "frameworks": [],
    },
    {
        "id": "python_ml",
        "name": "Python ML/Data",
        "category": "Data & ML",
        "icon": "BarChart3",
        "description": "Machine learning and data science",
        "frameworks": ["PyTorch", "TensorFlow", "scikit-learn", "pandas"],
    },
    {
        "id": "docker",
        "name": "Docker",
        "category": "DevOps",
        "icon": "Box",
        "description": "Dockerfiles and docker-compose",
        "frameworks": [],
    },
    {
        "id": "terraform",
        "name": "Terraform",
        "category": "DevOps",
        "icon": "Cloud",
        "description": "Infrastructure as Code with Terraform",
        "frameworks": [],
    },
    {
        "id": "github_actions",
        "name": "GitHub Actions",
        "category": "DevOps",
        "icon": "GitBranch",
        "description": "CI/CD workflows for GitHub",
        "frameworks": [],
    },
    {
        "id": "nextjs",
        "name": "Next.js",
        "category": "Fullstack",
        "icon": "Layers",
        "description": "Full-stack React with Next.js",
        "frameworks": ["App Router", "Pages Router"],
    },
    {
        "id": "t3_stack",
        "name": "T3 Stack",
        "category": "Fullstack",
        "icon": "Layers",
        "description": "Next.js + tRPC + Prisma + Tailwind",
        "frameworks": [],
    },
]
